# Generated by Django 3.2.4 on 2021-07-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_auto_20210717_1614'),
        ('frontlinerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='referrals.referral'),
        ),
    ]
