# Generated by Django 3.2.4 on 2021-08-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontlinerapp', '0002_profile_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
