# Generated by Django 3.2.4 on 2021-08-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontlinerapp', '0003_systemtransactions_systemwallet_usertransactions_userwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemtransactions',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='systemwallet',
            name='total_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='transaction_type',
            field=models.CharField(choices=[('DIRECT', 'DIRECT'), ('SPILL', 'SPILL'), ('WITHDRAWAL', 'WITHDRAWAL')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='total_balance',
            field=models.IntegerField(null=True),
        ),
    ]
