# Generated by Django 3.2.4 on 2021-08-09 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontlinerapp', '0004_auto_20210809_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='one_level_up_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_level_up_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_levels_up_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_levels_up_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
