# Generated by Django 3.2.4 on 2021-08-18 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontlinerapp', '0005_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
